# Generated by Django 3.1.3 on 2020-12-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20201206_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['created'], 'verbose_name': 'Categoria de Recetas', 'verbose_name_plural': 'Categorias'},
        ),
    ]
